language: java
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
script: jdk_switcher use oraclejdk8 && cd it.andreacioni.commons && mvn package install -DskipTests && cd .. && cd it.andreacioni.sdrive && mvn package assembly:single